# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7c1076ae9d349fc61701bd45fe87a046c778796bda91337e5a7824334fc5ad499fe761767e8f727cb4712cd08b3b71a6125d92d6e0ca682c39eb7d91cc81f33b

test:
  secret_key_base: 9b67f46c0d74958c23a750cb716005f1ae06f4e364ce4d076250b10066abf9a46edeba3ec752048e64da63e047111fc45814eef36cc6c71182504876885b4485

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
